name: PR Comment Triggered Lambda Deploy

on:
  issue_comment:
    types: [created]

jobs:
  deploy_lambda:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body || '', '/deploy') &&
      github.event.comment.user.type == 'User'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write  # Needed for commenting on PRs

    env:
      PR_NUMBER: ${{ github.event.issue.number }}  # Explicitly pass PR number

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head  # Correct branch reference
          fetch-depth: 0  # Ensure full history

      - name: Ensure PR is Approved
        id: check-approval
        uses: hmarr/auto-approve-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.issue.number }}  # Explicitly pass PR number

      - name: Deploy Lambda
        run: |
          echo "Deploying Lambda"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `✅ Lambda deployment triggered on \`${process.env.PR_NUMBER}\` branch!`
            });
