name: PR Comment Triggered Lambda Deploy

on:
  issue_comment:
    types: [created]

jobs:
  deploy_lambda:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/deploy') &&
      github.event.comment.user.type == 'User'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          fetch-depth: 0  # Ensures full history in case of branch switching

      - name: Ensure PR is Approved
        id: check-approval
        uses: hmarr/auto-approve-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Lambda
        run: |
          echo "Deploying Lambda"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.createComment({
              issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ Lambda deployment triggered on `${{ github.event.issue.pull_request.head.ref }}` branch!"
            });
