name: PR Comment Triggered Lambda Deploy

on:
  issue_comment:
    types: [created]

jobs:
  deploy_lambda:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/deploy') &&
      github.event.comment.user.type == 'User'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - name: Ensure PR is Approved
        id: check-approval
        uses: hmarr/auto-approve-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda
        run: |
          chmod +x deploy-lambda.sh
          ./deploy-lambda.sh
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.createComment({
              issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ Lambda deployment triggered!"
            });
