name: Super-Linter

on:
  push:
    branches:
      - main
      - develop  # Add other branches if needed
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Lints only changed files
          VALIDATE_JSCPD: false  # Disable duplicate code check (optional)
