name: Super-Linter

on:
  push:
    branches:
      - main
      - develop  # Add other branches if needed
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter (Ignore Failures)
        uses: super-linter/super-linter@v5
        continue-on-error: true  # Allows workflow to continue even if linting fails
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Lints only changed files
